### ISSUE TITLE
All subtitles are move in youtube.

### ISSUE THREAD

**Issue by semicolon3253** [arcusmaximus/YTSubConverter#10]
I make ass use aegisub. and I change ass to ytt use this tool.
But my subtitle is move in youtube when I put mouse cursor in youtube player.

And I test your sample ytt file(ytt.ytt/ https://github.com/arcusmaximus/YTSubConverter/blob/master/ytt.ytt)
But it move only bottom subtitle.

I am not good at English. So please watch this video: https://youtu.be/20lb7pxliWY
Thanks you.

**Comment by arcusmaximus** [comment]
The trick to prevent subtitles from moving on mouseover is to use a vertically centered alignment: `\an4`, `\an5` or `\an6`.

**Comment by Mizuhim3** [comment]
Just use \an7\an4 it will fix ur problem!
