### ISSUE TITLE
Can't find the .exe file for Windows

### ISSUE THREAD

**Issue by zengaku-henkin** [arcusmaximus/YTSubConverter#103]
I think there's supposed to be an executable to launch for the program, as was mentioned in the "Usage" section, but I couldn't find it in what I'd downloaded(Which I downloaded by clicking "Code" and "Download as ZIP file"). Am I blind, or is there no executable and if so, why?

**Comment by arcusmaximus** [comment]
Right above the "Usage" section title, there's a blue Download button.
