### ISSUE TITLE
Can't convert

### ISSUE THREAD

**Issue by emerald-teal** [arcusmaximus/YTSubConverter#13]
![image](https://user-images.githubusercontent.com/60566999/73606814-29eed280-457c-11ea-8d3a-a007bd932551.png)

I was making subtitles today and I went to YTSubConverter to convert my .ass to .ytt. However, this error popped up and I'm unable to convert this certain file. This has never happened before and all of my past files seem to work still; it's just this one file that I can't convert. What can I do to fix this? I've tried restarting my computer, and making a copy of the file and deleting the old one.

**Comment by arcusmaximus** [comment]
Please check whether the error still happens with the latest version of the converter (1.4.1). If it does, please share your .ass file so I can look into what's happening.

**Comment by emerald-teal** [comment]
Downloading the new version worked!! Thank you! I'm so happy

**Comment by emerald-teal** [comment]
For few days it worked fine, but it started popping up again with the same file. I honestly don't know what's going on.
I use:
 Aegisub 3.2.2
YTSubConverter 1.4.1
Windows 8.1
[hated.txt](https://github.com/arcusmaximus/YTSubConverter/files/4176402/hated.txt)

**Comment by emerald-teal** [comment]
New issue. A different error came up when I tried to convert an .sbv from YouTube to .ass. Like the other error, this happens only for a certain file. Is something wrong with my computer????
![img](https://user-images.githubusercontent.com/60566999/74095903-61ea9e00-4ac5-11ea-835f-2b22ac007b4d.png)

**Comment by arcusmaximus** [comment]
For hated.txt, I noticed you have a few `\t` tags where the ending time lies before the starting time (e.g. `\t(480,100,\c&H000000&\4c&HFFFFFF&)`). Try correcting or removing these.

For the .sbv conversion error, please attach that file too.

**Comment by emerald-teal** [comment]
Fixing the transitions worked! Thank you. 
I'm not sure on how to convert an .sbv file into a text file though.

**Comment by arcusmaximus** [comment]
Just rename it to .txt and attach it.

**Comment by arcusmaximus** [comment]
Could you attach the .sbv file that's failing to convert? Without the file, I can't see what the problem is.

**Comment by emerald-teal** [comment]
Sorry for the late reply, here is the .sbv file.
[heart.txt](https://github.com/arcusmaximus/YTSubConverter/files/4218666/heart.txt)

**Comment by arcusmaximus** [comment]
The error is caused by the empty line at 1:17. YTSubConverter thinks the "I just want to" is the start of a new subtitle and tries to read it as a time range, which of course fails.

For now, please remove the empty line between "(Blimp says TAB)" and "I just want to" (you can add it back after conversion). The next release of the converter will have this bug fixed.
