### ISSUE TITLE
Is .ytt -> .ass conversion possible?

### ISSUE THREAD

**Issue by Mmedic23** [arcusmaximus/YTSubConverter#17]
I've been looking into how I could convert srv3 subtitle files into a more friendly format when I came across your project.

I downloaded subtitle files for a video I want to watch offline with youtube-dl in multiple formats vtt, ttml, srv1, srv2 and srv3. The problem is, players don't support this format and there is no srv3 to ass converter that properly supports font, color, karaoke timings etc. Your project is the most competent and feature-complete program that deals with YouTube subtitle files so I thought I'd ask for help here. Is it possible to add a reverse conversion feature to the program?

Note: I've also looked at vtt to ass converters but no luck there either.

Thanks for your time!

**Comment by arcusmaximus** [comment]
Implemented two types of reverse conversion: one for editing and reuploading to YouTube, and one for archiving and watching locally. These are available in the new 1.5.0 release.

**Comment by Mmedic23** [comment]
Thank you man, works perfectly!
