### ISSUE TITLE
The mobile trick for dark text now affecting the desktop/browser Youtube player

### ISSUE THREAD

**Issue by AlphaPizza** [arcusmaximus/YTSubConverter#19]
**Version:** 1.4.3

**Description**
The trick with a bright layer on dark text made specifically for the mobile (Android) player (referring to [this](https://github.com/arcusmaximus/YTSubConverter/blob/b50ecb254926a8511820fbcb024180d2140d1f0b/YTSubConverter/Formats/YttDocument.cs#L266)) is, I believe, now messing up the Desktop/Browser version of the YouTube player since they now have issues with overlapping subtitles.

**Example:** https://youtu.be/fOnGxMtx6yU?t=44
The Black on White lines don't display properly (tested in Chrome and Firefox latest versions, on Windows 10). On the Android player, they are displayed with white texts (on the default black background).
I also think the issue [reported by this user on reddit](https://www.reddit.com/r/youtube/comments/grpwnz/youtube_broke_styled_subtitles_again/ftg95c6?utm_source=share&utm_medium=web2x) is because of this trick.

Unfortunately, removing the trick may mean that the YouTube app on Android would display unreadable lines. But keeping it means that it's the browser version that now have problems displaying the lines.
So unless YouTube decide to rollback or "fix" the issue on the desktop version, I don't know what would be the better approach to workaround this.

Maybe add an option on the UI to enabled or disable the Android hack and let the subtitler decide?
The UI could also display a popup warning the user that dark texts were detected in the styles and that it would be problematic on mobile app, and thus let them decided whether to change the problematic styles directly, or enable/disable the Android hack.

**Comment by arcusmaximus** [comment]
Fortunately, I was able to find and implement a workaround which prevents overlapping subtitles from flickering or disappearing. Please get the new 1.5.0 release.
