### ISSUE TITLE
Using the {\ytkt} tag will cause the whole line to use that karaoke type

### ISSUE THREAD

**Issue by Admiy02** [arcusmaximus/YTSubConverter#2]
Even a single {\ytkt} tag used on a line will cause the whole line to use that karaoke type. Using multiple {\ytkt} tags will cause the converter to only apply the last {\ytkt} tag in that line

**Comment by arcusmaximus** [comment]
Indeed - just like \pos and \fad, you can only have one \ytkt tag per line. This is by design. (The documentation mentions this too: "Configure the line to use ...")
