### ISSUE TITLE
Getting errors when trying to load a specific sub file (sub file and error message inside)

### ISSUE THREAD

**Issue by VoQZHD** [arcusmaximus/YTSubConverter#23]
![image](https://user-images.githubusercontent.com/45748775/91832033-85d22480-ec4d-11ea-83b6-f47f1e98f33d.png)

[過去に囚われている2.zip](https://github.com/arcusmaximus/YTSubConverter/files/5155222/2.zip)

**Comment by arcusmaximus** [comment]
Please check the lines with \ytchroma. They have an empty color (&H&) and are missing an alpha parameter.

**Comment by VoQZHD** [comment]
> Please check the lines with \ytchroma. They have an empty color (&H&) and are missing an alpha parameter.

This doesn't fix the problem

**Comment by VoQZHD** [comment]
> Please check the lines with \ytchroma. They have an empty color (&H&) and are missing an alpha parameter.

<3 thanks

**Comment by VoQZHD** [comment]
Setting it to \ytchroma(&H232225&, &HFFFFFF&, &H232225&, 255, 50, 50, 500, 500) didn't fix it for some reason
