### ISSUE TITLE
Outline gets enabled after converting

### ISSUE THREAD

**Issue by VoQZHD** [arcusmaximus/YTSubConverter#24]
[過去に囚われている.zip](https://github.com/arcusmaximus/YTSubConverter/files/5161125/default.zip)

**Comment by arcusmaximus** [comment]
Can you try deleting your StyleOptions.xml?

**Comment by VoQZHD** [comment]
> Can you try deleting your StyleOptions.xml?

Doesn't work. I tried different sub files and different styles yet it follows me each time

**Comment by arcusmaximus** [comment]
Hmm... Is this the kind of outline you're talking about - really thin and in multiple colors?
![test](https://user-images.githubusercontent.com/133129/92321937-788eae80-f02e-11ea-8e64-ba5668d624f1.png)
That seems to be some kind of font rendering bug. It happens in Firefox but not in Chrome, for example.

**Comment by VoQZHD** [comment]
> Hmm... Is this the kind of outline you're talking about - really thin and in multiple colors?
> ![test](https://user-images.githubusercontent.com/133129/92321937-788eae80-f02e-11ea-8e64-ba5668d624f1.png)
> That seems to be some kind of font rendering bug. It happens in Firefox but not in Chrome, for example.

I'm talking abut the youtube box to be precise (called it outline because outline controls it). For some reason it is being forced in chrome.

**Comment by VoQZHD** [comment]
> Hmm... Is this the kind of outline you're talking about - really thin and in multiple colors?
> ![test](https://user-images.githubusercontent.com/133129/92321937-788eae80-f02e-11ea-8e64-ba5668d624f1.png)
> That seems to be some kind of font rendering bug. It happens in Firefox but not in Chrome, for example.

When using firefox fonts are beeing ignored for some reason. This is very weird

**Comment by arcusmaximus** [comment]
Try resetting your subtitle options in both browsers. (Click the gear icon in the video player -> Subtitles -> Options -> Reset)

These options come with single-key keyboard shortcuts, so it's easy to change them by accident without even knowing they exist.

**Comment by VoQZHD** [comment]
Okay, thanks for helping. No idea what is it but I don't want to keep distracting you.

**Comment by arcusmaximus** [comment]
I take it it's still not fixed then?

Are you using the latest version of the converter? Did you try unchecking "Opaque box" in the Aegisub style options?

**Comment by VoQZHD** [comment]
I tested it with an opaque box on and off with both transparency 255 and 0 when it's disabled. Deleted styles and created them from zero, nothing changed. But I'm pretty sure its browser a related issue. Doesn't really matter anymore because they disabled community subs

**Comment by arcusmaximus** [comment]
Alright, sorry I couldn't help you then. The last thing I'd suggest is to try disabling any Chrome extensions you might have... Some of them are known to interfere with YouTube subtitles.

I'll close this ticket then.

(As for community subtitles: keep in mind that you can still send your .ytt file to the channel owner and ask them to upload it on  your behalf.)
