### ISSUE TITLE
Stationary text with {\an} and {\pos}

### ISSUE THREAD

**Issue by MikamiShuji** [arcusmaximus/YTSubConverter#27]
I know a similar issue had been brought up several times before, but all of them were only concerned with pretty basic prevention of movement on mouseover.
However, I've run into a situation where I need to achieve the same result with a custom position (slightly above the bottom center anchor point) to prevent overlap with hardcoded subs. Is there any combination of arguments in the .ytt format that would enable that? Converting with the tool so far yeilded no results - the position argument overrides the alignment and causes the text to move.

**Comment by arcusmaximus** [comment]
\pos in combination with \an5 should do the trick just fine. Here's an example that does just that: https://www.youtube.com/watch?v=6PQyYPMrzW0

**Comment by MikamiShuji** [comment]
Thank you very much. I've actually figured it out myself not too long ago, and it seems /an 4 and /an 6 seem to do the job as well while also aligning the text in a particular direction. 
I feel like this is somthing that's bound to be quite useful for a lot of users, but the current documentation doesn't really mention that anywhere. Perhaps it'd be best to mention that somewhere?

**Comment by arcusmaximus** [comment]
Glad to hear you got it working! The effects of alignment on subtitle movement are indeed not that obvious - I added them to the readme as part of the description of the \an tag.
