### ISSUE TITLE
Styling and visibility issues on Android 11

### ISSUE THREAD

**Issue by Madekuji** [arcusmaximus/YTSubConverter#28]
There seems to be an issue mostly on Android 11 devices in situations where subs are styled (such as karaoke subs). What will happen on Android 11 devices is that only one of the levels of subs would show up and the other one would not. Any alignment would also automatically be centered. This does not seem to be the case with Android 10 or below.

Examples: (Desktop at top, Android 11 at bottom)
![W7UqaYMVZJ](https://user-images.githubusercontent.com/27665110/107609413-c82a7380-6c79-11eb-8020-9472cb05a051.png)
![msedge_v64mrEcgpt](https://user-images.githubusercontent.com/27665110/107609559-3f600780-6c7a-11eb-80fb-63278c66f4ab.png)
![msedge_NsEpv3Be0O](https://user-images.githubusercontent.com/27665110/107609917-3ae81e80-6c7b-11eb-8dd3-4407b6502ec6.png)

If this is a YouTube issue, I'm wondering if there can be a workaround for this.

**Comment by arcusmaximus** [comment]
This is definitely a YouTube issue, yes. The mobile apps are pretty horrible when it comes to styled subtitles - in fact, the converter already contains a workaround for another Android bug (the app handles white text incorrectly, out of all things). Just like with the magically disappearing subtitles on iOS, however, I'm afraid I don't know how this one could be worked around. And going from past experience, YouTube will likely not be interested in fixing it either.

I added an additional warning to the "Limitations" section of the converter's documentation, but that's about all I can do. Sorry.

**Comment by arcusmaximus** [comment]
I got a report from another subtitle author that this bug may very well be a new one, introduced in version 16.06.33 of the app.

**Comment by cjbell630** [comment]
This is my first time testing it, so I can't confirm if it's new or not, but this is happening to me on Android 10 as well. No matter what I try, any positioning is completely wiped on the app, but looks fine on desktop. Could very easily just be a newbie problem though, idk. Way to go YouTube, ruining my dream of editable subs :(

**Comment by arcusmaximus** [comment]
Yes, most likely it's a bug in the YouTube app in general, unrelated to any particular Android version.

**Comment by arcusmaximus** [comment]
Update: amazingly, it seems YouTube fixed the problem. Let's hope they finally took this as a sign that they need to start testing a bit more.
