### ISSUE TITLE
failed to load object

### ISSUE THREAD

**Issue by gimmeAll** [arcusmaximus/YTSubConverter#30]
when i try loading an srv3 file, it gives me "Failed to load object: Object reference not set to an instance of an object" please help

**Comment by arcusmaximus** [comment]
Could you share the file that causes this error?

**Comment by gimmeAll** [comment]
https://drive.google.com/drive/folders/1XGyetOPh4g8mP-AIpC5Jtpvym4LtdPgj?usp=sharing

**Comment by arcusmaximus** [comment]
Thank you. It turns out the converter couldn't handle SRV3 files without styling. This will be fixed in the next release.

In the meantime, you can work around the error by opening the SRV3 file in Notepad and adding the text `<head/>` right before the `<body>`.

**Comment by gimmeAll** [comment]
thanks
