### ISSUE TITLE
cannot open a newer version

### ISSUE THREAD

**Issue by frezvent** [arcusmaximus/YTSubConverter#31]
I can't open version 1.5.0 and above, but the previous version can be opened pls help

**Comment by arcusmaximus** [comment]
Do you get any error message?

**Comment by frezvent** [comment]
no, just can't open it

**Comment by arcusmaximus** [comment]
So nothing happens at all if you doubleclick on it?

Are you maybe on an older Windows version? If so, please try updating your .NET framework installation.

**Comment by frezvent** [comment]
I'm using windows 10 and using .NET Framework 4.6.2, does it meet the requirements?,
I think it's weird if I can't open the latest version

**Comment by frezvent** [comment]
Are there any other applications needed to make this software run?

**Comment by arcusmaximus** [comment]
The latest versions of YTSubConverter depend on .NET 4.8.

**Comment by frezvent** [comment]
I've updated my .NET Framework and the software is running, I have one more question, how to change the language?

**Comment by arcusmaximus** [comment]
YTSubConverter automatically uses the language of your Windows installation if it's translated to that language. Currently the following languages are available: Chinese, Japanese, Korean, Malay, Polish and Russian. If your Windows installation uses another language, the converter will fall back to English.

If your language is not yet supported, feel free to create a pull request for adding it. You'd need to create new versions of the following files:
https://github.com/arcusmaximus/YTSubConverter/blob/master/YTSubConverter/Resources.resx
https://github.com/arcusmaximus/YTSubConverter/blob/master/YTSubConverter.UI/Resources.resx

The new files should have the language code in their name, such as the existing "Resources.ja.resx" for example.
