### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by ItsDrewfish** [arcusmaximus/YTSubConverter#33]
Hello! I am trying to make karaoke subtitles that highlight per syllable, but I can't seem to figure out how to get past this error: 
![image](https://user-images.githubusercontent.com/31579293/113484698-4407a600-94dc-11eb-8362-07c444d107e8.png)

**Comment by arcusmaximus** [comment]
Can you please share your .ass file?

**Comment by ItsDrewfish** [comment]
Here:
[a life that cannot contact you.zip](https://github.com/arcusmaximus/YTSubConverter/files/6253021/a.life.that.cannot.contact.you.zip)

**Comment by ItsDrewfish** [comment]
Looks like I can't even open files anymore on the program. 
![image](https://user-images.githubusercontent.com/31579293/113484905-6d750180-94dd-11eb-9a9e-bf10a206f15e.png)

**Comment by ItsDrewfish** [comment]
Update: I downloaded a new copy of the program and it worked flawlessly. I am so confused.

**Comment by arcusmaximus** [comment]
Most likely, the StyleOptions.xml got corrupted somehow. Redownloading the program to a different folder would result in a new StyleOptions.xml without the error being created.

I didn't get the error on my end, so let me know if you find a way of causing it again.

**Comment by ItsDrewfish** [comment]
Got it! Thanks for the info.

**Comment by HaleyHalcyon** [comment]
I'm getting this issue with the latest release 1.6.3. Here is the auto-generated StyleOptions:

```
<?xml version="1.0"?>
<StyleOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Style>
    <Name>Fake</Name>
    <ShadowType>None</ShadowType>
    <IsKaraoke>false</IsKaraoke>
    <CurrentWordTextColor />
    <CurrentWordOutlineColor />
    <CurrentWordShadowColor />
  </Style>
  <Style>
    <Name>Normal</Name>
    <ShadowType>Glow SoftShadow</ShadowType>
    <IsKaraoke>false</IsKaraoke>
    <CurrentWordTextColor />
    <CurrentWordOutlineColor />
    <CurrentWordShadowColor />
  </Style>
  <Style>
    <Name>TLNotes</Name>
    <ShadowType>Glow SoftShadow</ShadowType>
    <IsKaraoke>false</IsKaraoke>
    <CurrentWordTextColor />
    <CurrentWordOutlineColor />
    <CurrentWordShadowColor />
  </Style>
</StyleOptions>
```
