### ISSUE TITLE
Command line doesn't throw error

### ISSUE THREAD

**Issue by Graydenn** [arcusmaximus/YTSubConverter#34]
Hey,

Just a pretty simple issue. When using the program from the command line, it won't throw an error, it'll just have a blank line and then go back to allowing you to input a command without actually doing anything.

In this case, you have to throw the subs into the actual program to find out what was wrong with them- which is usually just a "&" somewhere.

Any chance of a fix for this?

**Comment by arcusmaximus** [comment]
Fixed - error messages now make it to the console window.
