### ISSUE TITLE
Cover Block didn't get converted properly

### ISSUE THREAD

**Issue by bagusnl** [arcusmaximus/YTSubConverter#37]
Sorry for my lack of term for the title, it might not make sense but I'll explain it here.

Take this video as example [Nanawo Akari's Turing Love](https://www.youtube.com/watch?v=L-MVk5I6wjo)
This video have a block that cover some parts of the video, basically to replace whatever the video has to the one provided by the subtitle file. On the srv file, it defined as spaces linked to the styling options, but the app didn't convert it properly so it doesn't block part of the video it supposed to causing some visual issue (duplicate text)
Images below

![image](https://user-images.githubusercontent.com/28079733/115176255-f489c280-a0f6-11eb-8b4d-91a00b3ab39a.png)
Left side is the expected result, you can see the green box behind the text to cover original video texts. On the right side, the greenbox didn't get converted properly, causing it to be impossible to read.
Just for a note, there is some broken parts on that video subtitle on YouTube that doesn't have cover blocks on it.

Anyways, thanks for making this, its a great piece of software!

**Comment by arcusmaximus** [comment]
This video is one of many affected by a bug that YouTube introduced last year. I reported it on Reddit back then, but to no avail:
https://www.reddit.com/r/youtube/comments/grpwnz/youtube_broke_styled_subtitles_again/

Since then, people found a workaround which I integrated in version 1.5.0 of the converter. That way, at least new subtitles will show up properly. (Old subtitles would have to be reconverted and reuploaded. Alternatively, YouTube could fix the bug, but at this point that's unlikely to happen.)

If you're still encountering this problem with the newest converter release, please share your .ass file.

**Comment by bagusnl** [comment]
> This video is one of many affected by a bug that YouTube introduced last year. I reported it on Reddit back then, but to no avail:
> https://www.reddit.com/r/youtube/comments/grpwnz/youtube_broke_styled_subtitles_again/

Ah yes, classic YouTube broke things again. Its so unfortunate styled subs like this got broken without any reasoning, WHILE also disabling community driven subtitles. Just plain shame on them.

> Since then, people found a workaround which I integrated in version 1.5.0 of the converter. That way, at least new subtitles will show up properly. (Old subtitles would have to be reconverted and reuploaded. Alternatively, YouTube could fix the bug, but at this point that's unlikely to happen.)
> 
> If you're still encountering this problem with the newest converter release, please share your .ass file.

I'm currently using the latest version of YTSubConverter (1.5.2) and I uploaded the ass file [here on gist](https://gist.github.com/bagusnl/85a7e3ffaa4904c7f521128c3438664f)

**Comment by arcusmaximus** [comment]
If I convert that .ass with 1.5.2 and load the result with Fiddler, the cover block works correctly.

Original:
![image](https://user-images.githubusercontent.com/133129/115217471-d7a8bb80-a105-11eb-8d01-e9dc60c761cd.png)

Reconversion loaded with Fidder:
![image](https://user-images.githubusercontent.com/133129/115217719-12125880-a106-11eb-845e-5440e06d3eee.png)

**Comment by bagusnl** [comment]
So is there any way to make the ass file works with regular player (I use MPC-HC Internal Subtitle Renderer, included in [K-lite Mega Codec Pack](http://www.codecguide.com/download_kl.htm) version 16.1.2

Also for different topic, I made Indonesian translation for it on my fork [here](https://github.com/bagusnl/YTSubConverter). I just had a little bit difficulty on testing it (no .NET SDK currently) and wrong commit comment, real noob with this kind of thing :^)

**Comment by arcusmaximus** [comment]
Aah I see, you're trying to reverse convert for local playback (.srv3 -> .ass), not forward convert for YouTube (.ass -> .srv3). My mistake - I didn't look closely enough at your screenshots.

Please see the readme section on reverse conversion: https://github.com/arcusmaximus/YTSubConverter#reverse-conversion
In short, the converter supports two kinds of reverse conversion, one for reuploading to YouTube and one for local playback. You did the first one, but you should be doing the second one.

As for your translation: feel free to create a pull request when you're done. I'll then integrate it and add your name to the credits at the end of the readme.

**Comment by bagusnl** [comment]
Ah, sorry for not reading the documentation properly. Got it working on my script now

```
youtube-dl -v --proxy "" --geo-bypass --skip-download --no-playlist --write-sub --sub-lang en,en-US,en-GB,ja,jp,id --sub-format srv3 %url%
for /r %%v in (*.srv) do YTSubConverter "%%v" --visual
```

Thank you so much!

Also I'll make pull request when I'm ready later
