### ISSUE TITLE
使用最新版1.5.3的一个瑕疵

### ISSUE THREAD

**Issue by amie1972** [arcusmaximus/YTSubConverter#38]
我使用aegisub设计好的竖排居中字幕，经过此软件转换之后再发布到youtube之后，出现了未预期的多余换行。https://www.youtube.com/watch?v=9ICg_ZCfY80
在第20秒处，本来应该是只有两行的，但是这个“鸟”字被放到了第三行。

**Comment by arcusmaximus** [comment]
It looks OK for me on Chrome and Firefox:
![image](https://user-images.githubusercontent.com/133129/124362796-7dfd5b00-dc37-11eb-9209-cc8826d1705b.png)

However, it's true that vertical subtitles sometimes get extra line breaks. It happens randomly and inconsistently. It's a bug in YouTube's code, and it's probably not possible to fix in YTSubConverter. Sorry.
