### ISSUE TITLE
Styling Problem

### ISSUE THREAD

**Issue by nyaasar** [arcusmaximus/YTSubConverter#4]
The subtitle preview didn't show any changes, can you help me with this? 

![image](https://user-images.githubusercontent.com/54396528/63502530-f4878880-c4f7-11e9-8b39-18969c99e3cd.png)

As you can see from the image above, the style i use should be looked like this.

![image](https://user-images.githubusercontent.com/54396528/63503061-f7cf4400-c4f8-11e9-8b95-708aefac9341.png)

And here's the preview from Aegisub, 

![image](https://user-images.githubusercontent.com/54396528/63503161-2a793c80-c4f9-11e9-997d-f4d54e4183f3.png)

I also upload the ASS file below, just rename it.
[Porter robinson Shelter done - Copy.txt](https://github.com/arcusmaximus/YTSubConverter/files/3529332/Porter.robinson.Shelter.done.-.Copy.txt)

And forgive me if there any errors in my writings. You see, English is not my ... thing. Thank you. 
Also, I use the newer version of YTSubConverter

**Comment by arcusmaximus** [comment]
Works for me:
![conv](https://user-images.githubusercontent.com/133129/63542584-00d40b80-c521-11e9-908e-60c8ce342dda.png)
Also when previewing the .ytt using Fiddler:
![yt](https://user-images.githubusercontent.com/133129/63542572-fa459400-c520-11e9-8d54-2739e04d6f50.png)

**Comment by nyaasar** [comment]
Hmm, that's weird. Maybe there's something wrong with my pc.
Btw, thanks for showing me the pict. I'll try it agin later.

**Comment by nyaasar** [comment]
Problem solved, this is the preview using Fiddler

![image](https://user-images.githubusercontent.com/54396528/63564067-bf2d7a00-c58d-11e9-9bd5-8cf23e7eb7c6.png)

I'm not sure what causing the YTSConverter preview not working in my pc. But it works on Youtube,
