### ISSUE TITLE
windows smartscreen on windows 8 considers it dangerous?

### ISSUE THREAD

**Issue by Noot-Toot** [arcusmaximus/YTSubConverter#42]
whenever i run the .exe from the download button in the readme, windows smartscreen just blocks it, i dont know what else i can say, but i can try to provide more

**Comment by arcusmaximus** [comment]
I'm guessing that more specifically, SmartScreen considers it "potentially" dangerous, which goes for any application it doesn't recognize. Any unknown application "might" be dangerous after all. I'm afraid there's not much I can do about this.

SmartScreen should offer you the option to ignore the warning and run the program anyway.
