### ISSUE TITLE
Big oof

### ISSUE THREAD

**Issue by RanHackett** [arcusmaximus/YTSubConverter#5]
Hello, I have used the YTT converter but when my caption was posed it has no animations, no color, no nothing. Like what? Here the video: (I can sent you the ASS + YTT file but I can't the usual button, so you have a Gmail?)

https://youtu.be/pfkBYHFZAt8

**Comment by nyaasar** [comment]
Upload the .ass and .ytt here. Just rename it to .txt

**Comment by nyaasar** [comment]
Upload the .ass and .ytt here. Just rename it to .txt

**Comment by arcusmaximus** [comment]
The most common cause for a lack of styling is changing something in YouTube's builtin subtitle editor after uploading the file. Adding even one space to a line will cause the editor to destroy any and all formatting (without telling you).

**Comment by nyaasar** [comment]
That's why I always add this line in my subtitle. Not really helpful though.

{\1a&HFF&\3a&HFF&}This is an Advanced SubStasion Alpha subtitle (.ytt). Do not edit on Youtube.

So that someone didn't edit the subtitle on YouTube.

**Comment by RanHackett** [comment]
OMG, I'm so sorry for not notice your message, I was super busy (I got like
got like 4 projects on the go right now), so please forgive me for being
neglected .

Yes, my problem, this just that, my YTT file works fine. But in the process
of voting someone edit it so It became corrupted, plus I can't seem to
understand the process of "fake voting" so that also a minus (if you can
help me out it would be wonderful). And, Ahhh... about the code, how
exactly you "add" it, sorry I don't get coding that much

Vào Th 3, 27 thg 8, 2019 vào lúc 04:18 nyaasar <notifications@github.com>
đã viết:

**Comment by RanHackett** [comment]
Also, here are the ASS and YTT file

Vào Th 3, 27 thg 8, 2019 vào lúc 18:34 Rated_R <randomguy2559@gmail.com>
đã viết:

**Comment by nyaasar** [comment]
Like this.

![image](https://user-images.githubusercontent.com/54396528/63777927-26d92180-c90e-11e9-8c16-c3b2087c1cdf.png)

**Comment by RanHackett** [comment]
Okay, thank you, but you still haven't teach me about "fake voting", plus
does the cap be corrupted if you remove a bank SubBox that not relate to
the main sub?

Vào Th 3, 27 thg 8, 2019 vào lúc 21:04 nyaasar <notifications@github.com>
đã viết:

**Comment by RanHackett** [comment]
Carp, at 2:01 of the caption, the fad code is visible, how can I fix it?!
https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&v=pfkBYHFZAt8&lang=en&bl=vmp&ui=hd&ref=player&tab=captions&o=U&ar=1566923006053&new=yes&captions-r=1

Vào Th 3, 27 thg 8, 2019 vào lúc 23:30 Rated_R <randomguy2559@gmail.com>
đã viết:
