### ISSUE TITLE
Duplicate lines

### ISSUE THREAD

**Issue by ThatOneJay** [arcusmaximus/YTSubConverter#50]
Every line is duplicated so there's repeating text on each line

![image](https://user-images.githubusercontent.com/76684256/139640703-29d85c36-be53-4779-a73a-328153b4aab5.png)

**Comment by arcusmaximus** [comment]
If you use multiple shadow types for a certain style, this behavior is completely normal and expected. YouTube subtitles only support one shadow type at a time, so if you enable multiple shadow types in YTSubConverter, it'll create multiple subtitles and layer them over each other to create the desired effect.
