### ISSUE TITLE
Support common keybinds/keyboard shortcuts

### ISSUE THREAD

**Issue by lae** [arcusmaximus/YTSubConverter#52]
I'd like to be able to perform some basic interactions with the application using keyboard shortcuts, namely the first that I missed was a `Ctrl+Q` keybind to quit the application. However, I think the following few might be useful to include as well for people using it:

`Ctrl+O` for opening a subtitle file
`Ctrl+S` for converting? My mental model basically thinks `Ctrl+S` for outputting out the .ytt file, but maybe a different one is better.
`Ctrl+A` for toggling autoconvert

P.S. Thanks for the Linux release. I actually wasn't expecting one and have been using YTSC in a Windows VM for a while, so this is really nice.

**Comment by arcusmaximus** [comment]
Thanks for the suggestion - I'm not a Linux user myself so I'm not really aware of the conventions there. All four shortcuts are now available on all platforms (except for Ctrl-Q on Windows, as there we already have the standard Alt-F4).

I'll probably publish a new release once I finish TTML support.

**Comment by arcusmaximus** [comment]
The new release is now available.
