### ISSUE TITLE
No executable for Linux in Linux release file?

### ISSUE THREAD

**Issue by Kazandu** [arcusmaximus/YTSubConverter#53]
![image](https://user-images.githubusercontent.com/14224126/142780926-b2addd81-c51f-45ae-b62b-72c2394bed46.png)
How do I use it in Linux? I cant find a executable file in the linux .tar.xz file...

**Comment by Kazandu** [comment]
After a bit of research i found out that you need mono to run it, maybe that should be added to the readme.

**Comment by arcusmaximus** [comment]
Sure - added a mention of Mono right before the download button.
