### ISSUE TITLE
Can't convert .ass file with opaque backgrounds

### ISSUE THREAD

**Issue by wavetro** [arcusmaximus/YTSubConverter#58]
So I have my subtitles configured like this to have opaque black backgrounds:

![image](https://user-images.githubusercontent.com/79939953/149686473-7f89134a-72fc-4673-b061-aeb8a3573913.png)

However, when I drag-and-drop the .ass file onto the program, the only options I have are soft shadows.

![image](https://user-images.githubusercontent.com/79939953/149686560-a324fff1-27e7-492d-b750-caf4e0f8118f.png)

Trying the "Autoconvert" and "Convert" buttons both give me .YTT files that only have these four soft drop shadows and not my desired black box backgrounds.

The readme/documentation page shows that having a solid box is a supported style with this program- how do I get YTSubConverter to keep my subtitles' backgrounds black and opaque? The only other styling I've been using is changing the primary color of the text with {\1c&HXXXXXX&} tags and nothing else. (using Aegisub on Linux and YTSubConverter on Windows)

**Comment by arcusmaximus** [comment]
To get a background box, please give the Aegisub style an Outline rather than a Shadow.
