### ISSUE TITLE
Output subtitle failed to load (cannot parse subtitle)

### ISSUE THREAD

**Issue by bagusnl** [arcusmaximus/YTSubConverter#59]
I noticed more recent YouTube srv3 subtitle breaks YTSubConverter output ssa files

An example is with this video https://www.youtube.com/watch?v=MxwV963ZNEU

Script that I used:
```
yt-dlp -v --cookies-from-browser "chrome" --skip-download --no-playlist --write-sub --sub-lang en,en-US,en-GB,ja,jp,id --sub-format srv3 %url%
for /r %%v in (*.srv3) do YTSubConverter --visual "%%v" 
```
Here's what I got with XySubFilter
![image](https://user-images.githubusercontent.com/28079733/157572661-2dd3435e-66de-4346-87a5-8aa5177978df.png)
![image](https://user-images.githubusercontent.com/28079733/157573208-f1961cd3-0e30-43be-bc03-98bfac1382e8.png)
A wrong line of subtitle does appear on the beginning, but after that, none appeared at all.
![image](https://user-images.githubusercontent.com/28079733/157573344-4d062998-f9a3-414d-8bb3-fefbe15c8eac.png)

Both ass and srv3 files is included in here https://gist.github.com/bagusnl/5a80264c19a07b1d2b06491944efd7f3

Notes:
YTSubConverter 1.6.0
MPC-HC 1.9.19.21
LAV 0.76.0.7-git
XySubFilter 3.2.0.806 (git)
madVR 0.92.17
Other subtitle filter can't load the ass either

**Comment by arcusmaximus** [comment]
This same issue was previously reported under #56. It was already fixed, but I hadn't published a new release yet. You can now get version 1.6.1 which has the fix included.
