### ISSUE TITLE
Odd position shifting during {\t} effects w/ alpha

### ISSUE THREAD

**Issue by Wat86** [arcusmaximus/YTSubConverter#69]
https://youtu.be/Oh_OEBGZCSM?t=109

Every subtitle here should be at position {\pos(590,880)} with {\an8}.
For whatever reason, whenever a \t effect that changes alpha is going on, it shifts the position of the line being changed by the effect (Not the entire subtitle) downwards, and it gets shifted back into position when the effect is over.

This only seems to be affecting this video for whatever reason;
https://youtu.be/oOUw68yWKO8?t=20 (This video uses a similar method but does not have this issue)

I've tried retyping in the entire subtitle, and deleted & redownloaded YTSubConverted, but the issue still persists.

**Comment by Wat86** [comment]
Upon further experimentation, it looks like this has something to do with font sizes.
The font size in the default "English" subtitles is set to be 15 with default's size being 20
The font size for the start of "English - Fade oddity test" is set to be 20 with a default's size being 20, and the bug goes away unless I change the font size back down to 15

perhaps something with the line spacing is going wrong during the \t effect?
I'll provide my .ass files used for testing

[cnpFADETEST.txt](https://github.com/arcusmaximus/YTSubConverter/files/8694001/cnpFADETEST.txt)
[cnpENStyleTestTWO.txt](https://github.com/arcusmaximus/YTSubConverter/files/8694002/cnpENStyleTestTWO.txt)

**Comment by arcusmaximus** [comment]
Fixed in the newly released 1.6.3 build. Thanks for reporting!
