### ISSUE TITLE
Documentation on the YTT format

### ISSUE THREAD

**Issue by sorenbug** [arcusmaximus/YTSubConverter#7]
Where can I find documentation on the YTT format? I'd like to be able to write my own program to be able to make subtitles.

**Comment by arcusmaximus** [comment]
I added a sample file to the repository that explains everything currently available in the format:
https://github.com/arcusmaximus/YTSubConverter/blob/master/ytt.ytt

**Comment by sorenbug** [comment]
Thank you, this is exactly what I need!
