### ISSUE TITLE
Youtube making unexpected changes to YTT subtitles again

### ISSUE THREAD

**Issue by Wat86** [arcusmaximus/YTSubConverter#70]
All styled subtitles using .ytt now seem to have this odd opaque block behind them, similarly to unstyled non .ytt format subtitles.
![image](https://user-images.githubusercontent.com/54781969/170839449-d5f6a3af-598c-4027-afe2-eb6e8ba0698a.png)
Example Video: https://www.youtube.com/watch?v=oOUw68yWKO8

**Comment by arcusmaximus** [comment]
This is (thankfully) not a global change that YouTube made, but a local change in your subtitle options. The YouTube player has a bunch of these options that most people even don't know exist, yet are very easy to change by accident (single keypress).

Follow these steps to reset the options and get the correct subtitle look again:
* Click the gear icon in the bottom right of the player
* Click "Subtitles/CC"
* Click the small "Options" link in the top right of the popup menu
* Scroll down in the options menu and click "Reset"

**Comment by Wat86** [comment]
Ah, thanks for the info! I was losing my mind thinking that everything broke for some reason.
Really odd that there's keybinds that can change how subtitles are handled.
