### ISSUE TITLE
YT Player Lags with Moving Lines

### ISSUE THREAD

**Issue by FloatingMind12** [arcusmaximus/YTSubConverter#72]
When the source .ass subtitle contains several moving lines rendering at the same time, YT player stick for some time
Such scenario can be reproduced using the example track below 
[Move.zip](https://github.com/arcusmaximus/YTSubConverter/files/8924153/Move.zip)
Maybe we could implement a proper line movement feature or instead convert them into static lines

**Comment by arcusmaximus** [comment]
If your subtitles are so complex that they make the YouTube player lag, you'll need to make them less complex.
If you want them to be static, simply leave out the `\ytmove` tag.
There's not much I can change in the converter to help with this.

**Comment by FloatingMind12** [comment]
When you said to leave out the \ytmove tag, where exactly?
I'm a bit confused here.

**Comment by arcusmaximus** [comment]
Sorry, I meant `\move` of course, not `\ytmove`.

**Comment by FloatingMind12** [comment]
Thanks anyway
I'm now thinking of making a script that would automatically simplify subtitles using 
[https://github.com/tkarabela/pysubs2](pysubs2)
