### ISSUE TITLE
Is it possible to write a Aegisub plugin that lets you use the custom yt tags YTSubConverter allows without converting to ytt and back to .ass?

### ISSUE THREAD

**Issue by a-rabin** [arcusmaximus/YTSubConverter#74]
Hello,
I wish to write a plugin that would let me use, for example, ytshake and other tags on a .ass subtitle without converting it to ytt and back to .ass.
Will it be possible?

Thanks

**Comment by arcusmaximus** [comment]
You could do that with a Lua script, yes. (I won't do it because this repository is all about the .ytt format)
