### ISSUE TITLE
The README needs to be updated on Fiddler on Firefox

### ISSUE THREAD

**Issue by a-rabin** [arcusmaximus/YTSubConverter#75]
Hello,
As o the latest versions of Firefox, installing a certificate manually to Firefox to enable Fiddler to work with subtitles is obsolete, as you cannot install certificates manually and the instructions on the fiddler website is obsolete. As such, the "additional steps on firefox" is not required.

Thanks.

**Comment by arcusmaximus** [comment]
Are you sure it's no longer needed? My Firefox still has a certificate manager with an Import button.

**Comment by a-rabin** [comment]
Yes but when I was setting it up I got stuck in that step as I could not find it as hard as I could. Then I said "screw it" and tried Fiddler without the certificate installed and it did work.
Another factor is that the Fiddler tutorial is very much obsolete as the settings and layouts are completely different, and I would assume things are much better now.

**Comment by arcusmaximus** [comment]
Readme updated.
