### ISSUE TITLE
Testing with Fiddler does not seem to work anymore?

### ISSUE THREAD

**Issue by mican8saku** [arcusmaximus/YTSubConverter#76]
The method of using Fiddler to test out previewing captions on other people's YouTube channels does not seem to be working as of August 2022. But I would like to get confirmation that this isn't just an issue on my side. I know that it worked because I was doing a translation project that used this method to preview about a year ago in June of 2021. But now I can't seem to get it to work. 

According to [this thread](https://stackoverflow.com/a/30601863) on stackoverflow the method of using "timedtext" to retrieve closed captions seem to have been discontinued by Google as of writing it in 2021 so I thought perhaps it could be related to the issue for Fiddler that uses a similar regex rule.
![image](https://user-images.githubusercontent.com/54508328/183251697-783dc1fd-db22-43a9-b774-19eb60d8ea75.png)

Wondering if there are any alternative methods of previewing or if anyone can confirm if it actually works or not.

**Comment by arcusmaximus** [comment]
I just tried it and it still seems to work, both on videos that already have subtitles and on videos that don't. All I can suggest is to recheck the Fiddler settings.

**Comment by mican8saku** [comment]
Thanks for the response! 
I got it to work when I tried it on a different browser instead. I just remembered that I was using Opera back then, before I switched over to Chrome. Not sure why I can't seem to get it to work in Chrome but at least now I have figured out a way around it.
