### ISSUE TITLE
Update Aegisub link in README

### ISSUE THREAD

**Issue by LibreSneed** [arcusmaximus/YTSubConverter#79]
https://github.com/arch1t3cht/Aegisub/ This fork of aegisub is actively maintained with new features being added and regular bug fixes. The one currently linked hasn't gotten a new release since almost 9 years and is incompatible with a lot of automation scripts

**Comment by arcusmaximus** [comment]
From the fork's readme:

> While this is usually also the version of Aegisub I'm currently using, I make no promises on stability. Don't use this version if you're just looking for any version of Aegisub - this is mostly intended for typesetting and other advanced usage.

This sounds a bit worrying, I'm afraid - not to mention that all those advanced typesetting features and scripts really aren't relevant for making YouTube subtitles. I updated the link to point to the wangqr fork instead (which was previously linked at the bottom of the page).
