### ISSUE TITLE
Style Preview Issue (not a big deal, but still)

### ISSUE THREAD

**Issue by nyaasar** [arcusmaximus/YTSubConverter#8]
Here's just the same old problem, not a big deal though. 

![image](https://user-images.githubusercontent.com/54396528/64132858-e4777f00-cdfc-11e9-9043-a8360bd72e13.png)

I'm using Fiddler for viewing my subs. The subtitles I uploaded is working great. Although it would be great if there any fix for this matter.

**Comment by arcusmaximus** [comment]
As mentioned in the other ticket, I've never had this problem. The only reason I can think of for it happening is that you have a really old version of Internet Explorer (which is what YTSubConverter uses for the preview pane). Which version do you have installed?

**Comment by nyaasar** [comment]
Holy ssss, so it's using IE for the preview panel. Hahaha... I guess the only problem is in my system.
I'm using Win 7 Ultimate and I've disabled my IE a long time ago. Now everything makes sense.
Alright then, I'll try something out.

**Comment by nyaasar** [comment]
GOOD NEWS!!

![image](https://user-images.githubusercontent.com/54396528/64192407-cd8c6780-cea4-11e9-8c02-42b945615e50.png)

I've updated my IE to the latest version available for my Win 7 and it works. Case closed!
