### ISSUE TITLE
Extending beyond borders

### ISSUE THREAD

**Issue by YabukiJoe** [arcusmaximus/YTSubConverter#81]
I have videos uploaded in aspect ratios thinner than 16:9, and I find that the subtitles tend to extend beyond the video frame. Is this meant to happen? Is it possible for me to set borders in the subtitle files so that this doesn't happen? I imagine this happens with 16:9 videos on ultrawide displays as well.

**Comment by arcusmaximus** [comment]
From YouTube's point of view, it's meant to be like this. (At least I think so - it wasn't the case on the classic website design. But good luck asking them about it, much less getting them to change it.)
It indeed also happens on 16:9 videos when enabling Theater Mode, even on 16:9 displays.

Sadly enough, YTSubConverter can't work around this. If it were possible, I would've implemented it a long time ago.
