### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by GXboy12345** [arcusmaximus/YTSubConverter#83]
When trying to convert .ass to .ytt, this error occurs:
`failed to load file: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index`
![image](https://github.com/arcusmaximus/YTSubConverter/assets/102619196/b47cc510-f45f-4c86-985e-24ffd5c9e4a9)

**Comment by arcusmaximus** [comment]
Please share your .ass file so I can reproduce the error and see where it's coming from.

**Comment by GXboy12345** [comment]
`
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Blue>Teal Roboto,Roboto,30,&H0090DD25,&H8BA6680B,&H00391606,&H00000000,0,0,0,0,275,275,0,0,1,3,1.5,2,18,18,15,1
Style: Translation,Times New Roman,30,&H0007886B,&H00378807,&H00032E19,&H00000000,0,0,0,0,275,275,0,0,1,3,1.5,8,18,18,15,1
Style: Kanji/Gana over,Arial,15,&H002D25DE,&H0011116E,&H00000000,&H00000000,0,0,0,0,275,275,0,0,1,3,3,2,18,18,45,1
Style: End Cred,Times New Roman,20,&H006163D7,&H000000FF,&H00000000,&H00000000,0,0,0,0,275,275,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.08,0:00:02.35,Blue>Teal Roboto,,0,0,0,,{\k0}{\k18}{\ytkt}{\ytktFade}{\fad(300,400)}ki{\k18}mi {\k20}no{\k50} ko{\k121}to
Dialogue: 0,0:00:00.08,0:00:02.35,Kanji/Gana over,,0,0,0,,{\k0}{\k18}{\ytkt}{\ytktFade}{\fad(300,400)}キ{\k18}ミ{\k20}の{\k50}こ{\k121}と
Dialogue: 0,0:00:00.08,0:00:02.35,Translation,,0,0,0,,{\fad(300,400)}Things about you,
Dialogue: 0,0:00:02.48,0:00:05.28,Blue>Teal Roboto,,0,0,0,,{\ytkt}{\ytktFade}{\k37}{\k16}{\fad(300,150)}wa{\k16}ta{\k25}shi {\k19}no {\k57}ko{\k110}to
Dialogue: 0,0:00:02.48,0:00:05.28,Kanji/Gana over,,0,0,0,,{\ytkt}{\ytktFade}{\k37}{\k16}{\fad(300,150)}わ{\k16}た{\k25}し{\k19}の{\k57}こ{\k110}と
Dialogue: 0,0:00:02.48,0:00:05.28,Translation,,0,0,0,,{\fad(300,150)}Things about me,
Dialogue: 0,0:00:05.35,0:00:08.35,Blue>Teal Roboto,,0,0,0,,{\k47}{\k19}{\ytkt}{\ytktFade}{\fad(300,150)}da{\k18}re{\k16}ka {\k22}no {\k54}ko{\k124}to
Dialogue: 0,0:00:05.35,0:00:08.35,Kanji/Gana over,,0,0,0,,{\k47}{\k19}{\ytkt}{\ytktFade}{\fad(300,150)}誰{\k18}{\k16}か{\k22}の{\k54}こ{\k124}と
Dialogue: 0,0:00:05.35,0:00:08.35,Translation,,0,0,0,,{\fad(300,150)}Things about someone,
Dialogue: 0,0:00:08.35,0:00:10.69,Blue>Teal Roboto,,0,0,0,,{\k33}{\k23}{\ytkt}{\ytktFade}{\fad(300,500)}shi{\k20}ra{\k20}na{\k17}i {\k59}ko{\k62}to
Dialogue: 0,0:00:08.35,0:00:10.69,Kanji/Gana over,,0,0,0,,{\k33}{\k23}{\ytkt}{\ytktFade}{\fad(300,500)}知{\k20}ら{\k20}な{\k17}い{\k59}こ{\k62}と
Dialogue: 0,0:00:08.35,0:00:10.69,Translation,,0,0,0,,{\fad(300,500)}Things that are unknown
Dialogue: 0,0:00:11.82,0:00:13.36,Blue>Teal Roboto,,0,0,0,,{\k4}{\k11}{\ytkt}{\ytktFade}{\fad(300,150)}o{\k27}shi{\k25}e{\k42}te {\k45}yo
Dialogue: 0,0:00:11.82,0:00:13.36,Kanji/Gana over,,0,0,0,,{\k4}{\k11}{\ytkt}{\ytktFade}{\fad(300,150)}教{\k27}{\k25}え{\k42}て{\k45}よ
Dialogue: 0,0:00:11.82,0:00:13.36,Translation,,0,0,0,,{\fad(300,150)}Tell me
Dialogue: 0,0:00:13.36,0:00:17.70,Blue>Teal Roboto,,0,0,0,,{\k35}{\k33}{\ytkt}{\ytktFade}{\fad(200,150)}ma{\k28}da {\k49}shi{\k53}ra{\k57}na{\k35}i {\k51}ha{\k16}na{\k77}shi
Dialogue: 0,0:00:13.36,0:00:17.70,Kanji/Gana over,,0,0,0,,{\k35}{\k33}{\ytkt}{\ytktFade}{\fad(200,150)}ま{\k28}だ{\k49}知{\k53}ら{\k57}な{\k35}い{\k51}話{\k16}{\k77}
Dialogue: 0,0:00:13.36,0:00:17.70,Translation,,0,0,0,,{\k35}{\k33}{\fad(200,150)}A story that I don't know yet
Dialogue: 0,0:00:17.70,0:00:20.20,Blue>Teal Roboto,,0,0,0,,{\k23}{\ytkt}{\ytktFade}{\fad(300,150)}ka{\k22}na{\k23}e{\k47}ru {\k40}ta{\k59}me {\k36}ni
Dialogue: 0,0:00:17.70,0:00:20.20,Kanji/Gana over,,0,0,0,,{\k23}{\ytkt}{\ytktFade}{\fad(300,150)}か{\k22}な{\k23}え{\k47}る{\k40}為{\k59}{\k36}に
Dialogue: 0,0:00:17.70,0:00:20.20,Translation,,0,0,0,,{\k23}{\ytktFade}{\fad(300,150)}In order to make it come true
Dialogue: 0,0:00:20.20,0:00:25.20,Blue>Teal Roboto,,0,0,0,,{\k14}{\k37}{\ytkt}{\ytktFade}{\fad(300,700)}i{\k168}ma {\k15}ko{\k20}ko{\k15}ro {\k18}hi{\k22}ra{\k38}i{\k153}te
Dialogue: 0,0:00:20.20,0:00:25.20,Kanji/Gana over,,0,0,0,,{\k14}{\k37}{\ytkt}{\ytktFade}{\fad(300,700)}い{\k168}ま{\k15}こ{\k20}こ{\k15}ろ{\k18}開{\k22}{\k38}い{\k153}て
Dialogue: 0,0:00:20.20,0:00:25.20,Translation,,0,0,0,,{\k14}{\k37}{\ytktFade}{\fad(300,700)}I now open up my heart
Dialogue: 0,0:00:25.20,0:00:29.14,Blue>Teal Roboto,,0,0,0,,{\fad(1000,1000)}{\ytchroma(20, 10, 1000, 1000)}{\move(355.556,90,888.889,90)}Subs by GXboy12345
Dialogue: 0,0:00:25.20,0:00:29.14,Translation,,0,0,0,,{\fad(1000,1000)}{\ytchroma(20, 10, 1000, 1000)}{\move(888.889,600,355.556,600)}字幕作成者: GXboy12345
Dialogue: 0,0:00:29.14,0:00:31.04,Blue>Teal Roboto,,0,0,0,,{\k32}{\k26}{\ytkt}{\ytktFade}{\fad(300,150)}sa{\k15}bi{\k39}shii {\k15}ku{\k38}se {\k25}ni
Dialogue: 0,0:00:29.14,0:00:31.04,Kanji/Gana over,,0,0,0,,{\k32}{\k26}{\ytkt}{\ytktFade}{\fad(300,150)}寂{\k15}{\k39}しい{\k15}く{\k38}せ{\k25}に
Dialogue: 0,0:00:29.14,0:00:31.04,Translation,,0,0,0,,{\k32}{\k26}{\ytkt}{\ytktFade}{\fad(300,150)}Even though I'm lonely
Dialogue: 0,0:00:29.14,0:00:31.04,Blue>Teal Roboto,,0,0,0,,{\fs10.5\pos(641.58,126.333)}{\fnCourier New}{\fad(300,150)}Note: next lines are in different language arrangement than English
Dialogue: 0,0:00:31.04,0:00:32.38,Blue>Teal Roboto,,0,0,0,,{\k25}{\ytkt}{\ytktFade}{\fad(300,150)}"ka{\k25}mat{\k25}te {\k10}ho{\k49}shii"
Dialogue: 0,0:00:31.04,0:00:32.38,Kanji/Gana over,,0,0,0,,{\k25}{\ytkt}{\ytktFade}{\fad(300,150)}「か{\k25}まっ{\k25}て{\k10}欲{\k49}しい」
Dialogue: 0,0:00:31.04,0:00:32.38,Translation,,0,0,0,,{\k25}{\fad(300,150)}how often have
Dialogue: 0,0:00:32.38,0:00:35.05,Blue>Teal Roboto,,0,0,0,,{\k35}{\ytkt}{\ytktFade}{\fad(300,150)}i{\k10}e{\k24}zu {\k20}ni {\k22}na{\k11}n{\k22}ka{\k22}i {\k12}ha{\k18}ni{\k19}ka{\k22}n{\k30}da
Dialogue: 0,0:00:32.38,0:00:35.05,Kanji/Gana over,,0,0,0,,{\k35}{\ytkt}{\ytktFade}{\fad(300,150)}言{\k10}え{\k24}ず{\k20}に{\k22}何{\k11}{\k22}回{\k22}{\k12}は{\k18}に{\k19}か{\k22}ん{\k30}だ
Dialogue: 0,0:00:32.38,0:00:35.05,Translation,,0,0,0,,{\k35}{\fad(300,150)}I been too shy to say
Dialogue: 0,0:00:35.21,0:00:36.65,Blue>Teal Roboto,,0,0,0,,{\k15}{\k23}{\ytkt}{\ytktFade}{\fad(300,150)}su{\k11}ko{\k28}shi {\k24}no {\k16}u{\k27}so
Dialogue: 0,0:00:35.21,0:00:36.65,Kanji/Gana over,,0,0,0,,{\k15}{\k23}{\ytkt}{\ytktFade}{\fad(300,150)}少{\k11}{\k28}し{\k24}の{\k16}噓{\k27}
Dialogue: 0,0:00:35.21,0:00:36.65,Translation,,0,0,0,,{\k15}{\k23}{\ytktFade}{\fad(300,150)}"I want you to pay attention to me"
Dialogue: 0,0:00:36.65,0:00:38.38,Blue>Teal Roboto,,0,0,0,,{\k27}{\ytkt}{\ytktFade}{\fad(100,150)}wa {\k18}do{\k9}u{\k25}se {\k21}na{\k25}ra {\k30}mot{\k18}to
Dialogue: 0,0:00:36.65,0:00:38.38,Kanji/Gana over,,0,0,0,,{\k27}{\ytkt}{\ytktFade}{\fad(100,150)}わ{\k18}ど{\k9}う{\k25}せ{\k21}な{\k25}ら{\k30}もっ{\k18}と
Dialogue: 0,0:00:36.65,0:00:38.38,Translation,,0,0,0,,{\k27}{\ytktFade}{\fad(100,150)}If I'm going to tell a little lie anyway
Dialogue: 0,0:00:38.38,0:00:41.05,Blue>Teal Roboto,,0,0,0,,{\k52}{\ytkt}{\ytktFade}{\fad(300,500)}u{\k15}ma{\k8}ku {\k45}tsu{\k21}ka{\k10}e{\k33}ru {\k38}no {\k45}ni
Dialogue: 0,0:00:38.38,0:00:41.05,Kanji/Gana over,,0,0,0,,{\k52}{\ytkt}{\ytktFade}{\fad(300,500)}上手{\k15}{\k8}く{\k45}使{\k21}{\k10}え{\k33}る{\k38}の{\k45}に
Dialogue: 0,0:00:38.38,0:00:41.05,Translation,,0,0,0,,{\k55}{\ytktFade}{\fad(300,500)}I could do so more skillfully, but...
Dialogue: 0,0:00:41.05,0:00:46.39,Blue>Teal Roboto,,0,0,0,,{\k37}{\k9}{\ytktFade}{\fad(300,600)}ma{\k22}ji{\k15}ma{\k45}ji {\k46}to {\k58}i{\k37}ki{\k18}te {\k19}i{\k37}ta{\k191}ra
Dialogue: 0,0:00:41.05,0:00:46.39,Kanji/Gana over,,0,0,0,,{\k37}{\k9}{\ytktFade}{\fad(300,600)}ま{\k22}じ{\k15}ま{\k45}じ{\k46}と{\k58}生{\k37}き{\k18}て{\k19}い{\k37}た{\k191}ら
Dialogue: 0,0:00:41.05,0:00:46.39,Translation,,0,0,0,,{\k37}{\k9}{\ytktFade}{\fad(300,600)}Living my life nervously
Dialogue: 0,0:00:46.69,0:00:52.23,Blue>Teal Roboto,,0,0,0,,{\k53}{\k23}{\ytktFade}{\fad(500,200)}ka{\k19}ba {\k16}ba{\k33}ka{\k39}ri {\k15}ga {\k59}mi{\k23}e{\k46}te {\k24}ki{\k204}te
Dialogue: 0,0:00:46.69,0:00:52.23,Kanji/Gana over,,0,0,0,,{\k53}{\k23}{\ytktFade}{\fad(500,200)}壁{\k19}{\k16}ば{\k33}か{\k39}り{\k15}が{\k59}見{\k23}え{\k46}て{\k24}き{\k204}て
Dialogue: 0,0:00:46.69,0:00:52.23,Translation,,0,0,0,,{\k53}{\k23}{\ytktFade}{\fad(500,200)}I see nothing but walls ahead
Dialogue: 0,0:00:53.03,0:00:57.74,Blue>Teal Roboto,,0,0,0,,{\k5}{\k20}{\ytktFade}{\fad(300,150)}ki {\k13}ga {\k25}tsu{\k60}ke{\k38}ba {\k51}ra{\k31}bi{\k46}ri{\k9}n{\k173}su
Dialogue: 0,0:00:53.03,0:00:57.74,Kanji/Gana over,,0,0,0,,{\k5}{\k20}{\ytktFade}{\fad(300,150)}気{\k13}が{\k25}つ{\k60}け{\k38}ば{\k51}ラー{\k31}ビ{\k46}リ{\k9}ン{\k173}ス
Dialogue: 0,0:00:53.03,0:00:57.74,Translation,,0,0,0,,{\k5}{\k20}{\ytktFade}{\fad(300,150)}And just like that, I find myself in a labyrinth
Dialogue: 0,0:00:57.74,0:01:00.41,Blue>Teal Roboto,,0,0,0,,{\k7}{\k43}{\ytktFade}{\fad(300,150)}so{\k22}n{\k35}na {\k35}ji{\k11}n{\k42}se{\k36}i {\k36}wa
Dialogue: 0,0:00:57.74,0:01:00.41,Kanji/Gana over,,0,0,0,,{\k7}{\k43}{\ytktFade}{\fad(300,150)}そ{\k22}ん{\k35}な{\k35}人{\k11}{\k42}生{\k36}{\k36}は
Dialogue: 0,0:00:57.74,0:01:00.41,Translation,,0,0,0,,{\k7}{\k43}{\ytktFade}{\fad(300,150)}A life like that...
Dialogue: 0,0:01:01.04,0:01:01.97,Blue>Teal Roboto,,0,0,0,,{\k15}{\k20}{\ytktFade}{\fad(300,100)}ya {\k35}da {\k23}yo!
Dialogue: 0,0:01:01.04,0:01:01.97,Kanji/Gana over,,0,0,0,,{\k15}{\k20}{\ytktFade}{\fad(300,100)}ヤ{\k35}ダ{\k23}よ！
Dialogue: 0,0:01:01.04,0:01:01.97,Translation,,0,0,0,,{\k15}{\k20}{\ytktFade}{\fad(300,100)}I don't want!
Dialogue: 0,0:01:01.97,0:01:03.41,Blue>Teal Roboto,,0,0,0,,{\k10}{\ytktFade}{\fad(100,150)}mo{\k18}shi {\k16}so{\k69}re {\k31}ga
Dialogue: 0,0:01:01.97,0:01:03.41,Kanji/Gana over,,0,0,0,,{\k10}{\ytktFade}{\fad(100,150)}も{\k18}し{\k16}そ{\k69}れ{\k31}が
Dialogue: 0,0:01:01.97,0:01:03.41,Translation,,0,0,0,,{\k10}{\ytktFade}{\fad(100,150)}If that person is
Dialogue: 0,0:01:03.41,0:01:07.75,Blue>Teal Roboto,,0,0,0,,{\k43}{\k30}{\ytktFade}{\fad(300,150)}"ma{\k28}da{\k50} shi{\k35}ra{\k68}na{\k37}i{\k41} wa{\k27}ta{\k75}shi"
Dialogue: 0,0:01:03.41,0:01:07.75,Kanji/Gana over,,0,0,0,,{\k43}{\k30}{\ytktFade}{\fad(300,150)}「ま{\k28}だ{\k50}知{\k35}ら{\k68}な{\k37}い{\k41}私」{\k27}{\k75}
Dialogue: 0,0:01:03.41,0:01:07.75,Translation,,0,0,0,,{\k43}{\k30}{\ytktFade}{\fad(300,150)}"The me that I don't know yet"
Dialogue: 0,0:01:07.75,0:01:12.25,Blue>Teal Roboto,,0,0,0,,{\k12}{\k16}{\ytktFade}{\fad(200,150)}na{\k24}ra{\k22}ba {\k46}mo{\k36}u {\k44}a{\k75}shi{\k35}ta {\k140}wa
Dialogue: 0,0:01:07.75,0:01:12.25,Kanji/Gana over,,0,0,0,,{\k12}{\k16}{\ytktFade}{\fad(200,150)}な{\k24}ら{\k22}ば{\k46}も{\k36}う{\k44}明{\k75}{\k35}日{\k140}は
Dialogue: 0,0:01:07.75,0:01:12.25,Translation,,0,0,0,,{\k12}{\k16}{\ytktFade}{\fad(200,150)}Then tomorrow...
Dialogue: 0,0:01:12.25,0:01:16.76,Blue>Teal Roboto,,0,0,0,,{\k14}{\k18}{\ytktFade}{\fad(300,150)}su{\k13}ko{\k24}shi {\k18}mi{\k26}ryo{\k36}ku{\k24}te{\k13}ki {\k36}ni {\k37}na{\k192}ru
Dialogue: 0,0:01:12.25,0:01:16.76,Kanji/Gana over,,0,0,0,,{\k14}{\k18}{\ytktFade}{\fad(300,150)}少{\k13}{\k24}し{\k18}魅{\k26}力{\k36}{\k24}{\k13}的{\k36}に{\k37}な{\k192}る
Dialogue: 0,0:01:12.25,0:01:16.76,Translation,,0,0,0,,{\k14}{\k18}{\ytktFade}{\fad(300,150)}Should be more appealing to me
Dialogue: 0,0:01:19.39,0:01:26.68,Blue>Teal Roboto,,0,0,0,,{\k19}{\k19}{\ytktFade}{\fad(400,900)}be{\k19}ki {\k21}de {\k53}a{\k473}ru
Dialogue: 0,0:01:19.39,0:01:26.68,Kanji/Gana over,,0,0,0,,{\k19}{\k19}{\ytktFade}{\fad(400,900)}べ{\k19}き{\k21}で{\k53}あ{\k473}る
Dialogue: 0,0:01:19.39,0:01:26.68,Translation,,0,0,0,,{\k19}{\k19}{\ytktFade}{\fad(400,900)}It should be
Dialogue: 0,0:01:26.68,0:01:29.68,End Cred,,0,0,0,,{\fad(300,300)\pos(512,56)}Subtitles by @GXboy12345 (discord)
`

**Comment by arcusmaximus** [comment]
Thank you. The error is caused by the empty `{\ytkt}` tags - try removing those, leaving just the `{\ytktFade}` ones.

**Comment by GXboy12345** [comment]
Ah.

**Comment by GXboy12345** [comment]
Worked, thanks :)
