### ISSUE TITLE
Permanently stationary subtitles?

### ISSUE THREAD

**Issue by thegreatestminer** [arcusmaximus/YTSubConverter#9]
I've seen taringtajam do it on various videos, but I never could figure it out.

Manually setting `{\pos}` does nothing, so is there another tag, or am I just blind?

(aka the player controls do not move the subtitles like regular nonstyled subtitles)

**Comment by arcusmaximus** [comment]
The trick to create stationary subtitles is to use a vertically centered alignment: `\an4`, `\an5` or `\an6`.

**Comment by thegreatestminer** [comment]
Awesome, thanks for this.
