### ISSUE TITLE
Foreign characters are not supported

### ISSUE THREAD

**Issue by fernzhn** [arcusmaximus/YTSubConverter#95]
Hi there! I have created a subtitle peace in Subtitle Edit, with foreign characters, as the Hungarian language usually requires it (á, é, í, ó, ö, ő, ú, ü, ű), but after converting the .ass file to the YouTube style, and uploading it to YouTube, it doesn't seem to be able to recognize those characters, and puts a [?] in their place. Any idea how to fix this? Thank you.
![image](https://github.com/arcusmaximus/YTSubConverter/assets/167031843/fcfe45cb-b396-4f9c-bdd4-83fcf74e2ea5)
![image](https://github.com/arcusmaximus/YTSubConverter/assets/167031843/175f8fc8-9f27-4038-a983-c5cc7eb24e9f)

**Comment by arcusmaximus** [comment]
YTSubConverter supports foreign characters - it's been used for Asian languages for a long time. Most likely, Subtitle Edit is saving the .ass file with the wrong encoding (should be UTF8).

**Comment by fernzhn** [comment]
I believe I had it set it up for UTF-8, but I can re check it in a few hours.

**Comment by fernzhn** [comment]
It looks like the encoding was really wrong. Weirdly enough, when I saved the subtitle, I set it to UTF-8, most likely it changed back to the previous one. It works now, the program was just being weird a little for me. Thank you, have a nice day!
